/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.views;

import app.controllers.ReportsController;
import app.helpers.Callback;
import app.helpers.ReportType;
import app.helpers.SystemReport;
import app.helpers.renderers.ReportSelectionListCellRenderer;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.decorator.HighlighterFactory;

/**
 *
 * @author Isuru
 */
public class Reports extends javax.swing.JDialog {

    /**
     * Creates new form Reports
     */
    public Reports(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        reports_selection_list.setHighlighters(HighlighterFactory.createAlternateStriping());
        reports_selection_list.setCellRenderer(new ReportSelectionListCellRenderer("report.png", "report_go.png"));
        cover_overlay.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        coverlabel.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        // fill report categories
        fillReportCategories();
        loadReportsForCategory();
    }

    private void fillReportCategories() {
        DefaultComboBoxModel def = (DefaultComboBoxModel) cmb_report_types.getModel();
        ReportType[] rtypes = ReportType.values();
        for (ReportType rtype : rtypes) {
            def.addElement(rtype);
        }
    }

    private void loadReportsForCategory() {
        if (cmb_report_types.getSelectedIndex() == -1) {
            return;
        }
        ArrayList<SystemReport> rlist = new ArrayList<>();
        ReportType rty = (ReportType) cmb_report_types.getSelectedItem();
        SystemReport[] reports = SystemReport.values();
        for (SystemReport sysrp : reports) {
            if (sysrp.getRtype().equals(rty) && sysrp.isActive()) {
                rlist.add(sysrp);
            }
        }
        reports_selection_list.setListData(rlist.toArray());
    }

    private void _viewReport(final SystemReport systemReport, final HashMap<String, Object> params) {
        try {
            new Thread(new Runnable() {

                @Override
                public void run() {
                    setGlassPane(cover_overlay);
                    getGlassPane().setVisible(true);
                    gen_report.setEnabled(false);
                    ReportsController.prepareAndViewReport(systemReport, params);
                    gen_report.setEnabled(true);
                    getGlassPane().setVisible(false);
                }
            }).start();
        } catch (Exception e) {
            getGlassPane().setVisible(false);
        }
    }

    private void _viewReport(final SystemReport systemReport, final HashMap<String, Object> params, final Callback runBefore) {
        try {
            new Thread(new Runnable() {

                @Override
                public void run() {
                    setGlassPane(cover_overlay);
                    getGlassPane().setVisible(true);
                    gen_report.setEnabled(false);
                    runBefore.run();
                    ReportsController.prepareAndViewReport(systemReport, params);
                    gen_report.setEnabled(true);
                    getGlassPane().setVisible(false);
                }
            }).start();
        } catch (Exception e) {
            getGlassPane().setVisible(false);
        }
    }


    /**
     * Preview/print selected report We have to add the report to this function
     * in order to preview
     */
    private void showReport(final SystemReport systemReport) {
        final HashMap<String, Object> params = new HashMap<>();
        final File f = new File("reports");
        final String SUBREPORT_DIR = f.getAbsolutePath() + "\\";
        params.put("SUBREPORT_DIR", SUBREPORT_DIR);
        switch (systemReport) {
           default: {}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cover_overlay = new javax.swing.JPanel();
        coverlabel = new javax.swing.JLabel();
        period_selector = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        start_date = new com.toedter.calendar.JDateChooser();
        end_date = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        months_selector = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        month_year_selection = new com.toedter.calendar.JYearChooser();
        month_month_selection = new com.toedter.calendar.JMonthChooser();
        date_selection_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        cmb_report_types = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        gen_report = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reportdesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reports_selection_list = new org.jdesktop.swingx.JXList();
        jLabel3 = new javax.swing.JLabel();

        cover_overlay.setBackground(new java.awt.Color(18, 18, 18));

        coverlabel.setBackground(new java.awt.Color(18, 18, 18));
        coverlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coverlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resources/Load002.gif"))); // NOI18N

        javax.swing.GroupLayout cover_overlayLayout = new javax.swing.GroupLayout(cover_overlay);
        cover_overlay.setLayout(cover_overlayLayout);
        cover_overlayLayout.setHorizontalGroup(
            cover_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cover_overlayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coverlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        cover_overlayLayout.setVerticalGroup(
            cover_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cover_overlayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coverlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Select report period: ");

        start_date.setDateFormatString("yyyy-MM-dd");

        end_date.setDateFormatString("yyyy-MM-dd");

        jLabel6.setText("From: ");

        jLabel7.setText("To : ");

        javax.swing.GroupLayout period_selectorLayout = new javax.swing.GroupLayout(period_selector);
        period_selector.setLayout(period_selectorLayout);
        period_selectorLayout.setHorizontalGroup(
            period_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(period_selectorLayout.createSequentialGroup()
                .addGroup(period_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(period_selectorLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end_date, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        period_selectorLayout.setVerticalGroup(
            period_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(period_selectorLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(period_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(period_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(start_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(end_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jLabel9.setText("Select target month : ");

        javax.swing.GroupLayout months_selectorLayout = new javax.swing.GroupLayout(months_selector);
        months_selector.setLayout(months_selectorLayout);
        months_selectorLayout.setHorizontalGroup(
            months_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9)
            .addGroup(months_selectorLayout.createSequentialGroup()
                .addComponent(month_year_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(month_month_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        months_selectorLayout.setVerticalGroup(
            months_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(months_selectorLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(months_selectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(month_year_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month_month_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel5.setText("Select target date : ");

        javax.swing.GroupLayout date_selection_panelLayout = new javax.swing.GroupLayout(date_selection_panel);
        date_selection_panel.setLayout(date_selection_panelLayout);
        date_selection_panelLayout.setHorizontalGroup(
            date_selection_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        date_selection_panelLayout.setVerticalGroup(
            date_selection_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(date_selection_panelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reports");

        cmb_report_types.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_report_typesItemStateChanged(evt);
            }
        });

        jLabel1.setText("Report Type : ");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gen_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resources/accept.png"))); // NOI18N
        gen_report.setText("Generate Report");
        gen_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gen_reportActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Description : ");

        reportdesc.setText("Please select a report to see the description.");
        reportdesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportdesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(reportdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        reports_selection_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reports_selection_list.setFixedCellHeight(30);
        reports_selection_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reports_selection_listMouseClicked(evt);
            }
        });
        reports_selection_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reports_selection_listKeyPressed(evt);
            }
        });
        reports_selection_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reports_selection_listValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(reports_selection_list);

        jLabel3.setBackground(new java.awt.Color(36, 114, 191));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reports");
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(242, 130, 27)), javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 10)));
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_report_types, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gen_report)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_report_types, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(gen_report))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_report_typesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_report_typesItemStateChanged
        // load reports list for the selected category
        loadReportsForCategory();
    }//GEN-LAST:event_cmb_report_typesItemStateChanged

    private void gen_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gen_reportActionPerformed
        //print the selected report on button click
        if (reports_selection_list.getSelectedIndex() > -1) {
            //get selected report from the list
            SystemReport sysrp = (SystemReport) reports_selection_list.getSelectedValue();
            //show the report preview
            showReport(sysrp);
        }
    }//GEN-LAST:event_gen_reportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reports_selection_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reports_selection_listValueChanged
        if (reports_selection_list.getSelectedIndex() > -1) {
            SystemReport sysrp = (SystemReport) reports_selection_list.getSelectedValue();
            reportdesc.setText("<html>" + sysrp.getReportDescription());
        } else {
            reportdesc.setText("Please select a report to see the description.");
        }
    }//GEN-LAST:event_reports_selection_listValueChanged

    private void reports_selection_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports_selection_listMouseClicked
        if (evt.getClickCount() > 1) {
            if (reports_selection_list.getSelectedIndex() > -1) {
                SystemReport sysrp = (SystemReport) reports_selection_list.getSelectedValue();
                showReport(sysrp);
            }
        }
    }//GEN-LAST:event_reports_selection_listMouseClicked

    private void reports_selection_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reports_selection_listKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            if (reports_selection_list.getSelectedIndex() > -1) {
                SystemReport sysrp = (SystemReport) reports_selection_list.getSelectedValue();
                showReport(sysrp);
            }
        }
    }//GEN-LAST:event_reports_selection_listKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reports dialog = new Reports(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_report_types;
    private javax.swing.JPanel cover_overlay;
    private javax.swing.JLabel coverlabel;
    private javax.swing.JPanel date_selection_panel;
    private com.toedter.calendar.JDateChooser end_date;
    private javax.swing.JButton gen_report;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JMonthChooser month_month_selection;
    private com.toedter.calendar.JYearChooser month_year_selection;
    private javax.swing.JPanel months_selector;
    private javax.swing.JPanel period_selector;
    private javax.swing.JLabel reportdesc;
    private org.jdesktop.swingx.JXList reports_selection_list;
    private com.toedter.calendar.JDateChooser start_date;
    // End of variables declaration//GEN-END:variables
}
